plugins:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'

# Layout
Layout/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

# Metrics
Metrics/ClassLength:
  Max: 200
  CountComments: false
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Metrics/ModuleLength:
  Max: 200
  CountComments: false
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Metrics/MethodLength:
  Max: 15
  CountComments: false
  AllowedMethods:
    - 'initialize'
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Metrics/CyclomaticComplexity:
  Max: 8
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Metrics/PerceivedComplexity:
  Max: 9
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Metrics/ParameterLists:
  Max: 4
  CountKeywordArgs: false
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

Metrics/BlockLength:
  Max: 35
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

# Style
Style/Documentation:
  Enabled: true
  Exclude:
    - 'spec/**/*'

Style/StringLiterals:
  EnforcedStyle: single_quotes
  ConsistentQuotesInMultiline: true

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/GuardClause:
  Enabled: true
  MinBodyLength: 1

Style/ModuleFunction:
  Enabled: true
  EnforcedStyle: module_function

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

# Security
Security/Eval:
  Enabled: true

Security/Open:
  Enabled: true

# Performance
Performance/Count:
  Enabled: true

Performance/Detect:
  Enabled: true

# Additional cops
Lint/UselessAssignment:
  Enabled: true

Lint/DuplicateMethods:
  Enabled: true

Rails:
  Enabled: false
